### ISSUE TITLE
Spustanie procesov nema osetreny stav ak proces nedobehne (caka thread blokujuco na p.waitFor) cim moze dojst k vyzratiu threadov na serveri

### ISSUE THREAD

**Issue by hhulwath** [lisymart/Neck#1]
doporucujem pouzit:
https://github.com/zeroturnaround/zt-exec

**Comment by lisymart** [comment]
Chapem, navrhujete nastavit cas, ktory ked bude prekroceny dojde k ukonceniu vlakna? 
Alebo nieco ine?

**Comment by hhulwath** [comment]
Nikdy nie je dobry napad blokovat thread donekonecna, duplom ak robite taku nebezpecnu vec ako ze volate externy proces, teda nieco co nie je pod spravou jvm.
zt-exec nic nevyriesi som od seba ;-) ale celkom elegantne vam dovoli nastavit ten timeout a zaroven ked si precitate k nemu dokumentaciu/javadoc mozno vas napadne co vsetko este by ste mali nejako riesit (ze ten externy proces dobehol, nikdy nedobehol, dobehol s nejakou chybou, dobehol s nejakym exit code, bezi uz straaaasne dlho, .....
  
a btw, logujte cez http://www.slf4j.org/ a http://logback.qos.ch/, java.util.logging som snad poslednych 10 rokov ani nepouzil
a ked najdete toto: https://github.com/logstash/logstash-logback-encoder/tree/logstash-logback-encoder-4.7 tak davajte pozor aby ste z mladickej nerozvaznosti svoje prevadzkove logy - teda co sa u vas v aplikacii deje - nepisali do toho isteho ELKu kde zapisujete informacie co vasa aplikacia riesi ako biznis zadanie. potom by ste mohli dopadnut ako v tom vtipe o tom ze: hrkoce ti retaz, nepocujem, hrkoce mi retaz
teda keby ten ELK do ktoreho pisete biznis data bol napriklad pretazeny alebo mal nejaky problem, tak vasa aplikacia by ho dorazila este tym ze by sa snazila do neho zalogovat ze nefunguje
Zaroven bacha ak sa odvazite logovat okrem do suboru aj do nejakeho ineho , prevadzkoveho, ELKu, tak cez nejaky apender co neblokne vasu aplikaciu . bolo by smutne ak by aplikacia zase bola zablokovana lebo nevedela zalogovat

a na zistenie ci elasticksearch bezi skuste nieco taketo: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html Nikdy som to neskusal a mozno vo vasom setupe sa to zistuje nejako inak ale v kazdom systeme mal by existovat nejaky health endpoint kde sa da zistit ci nejaky system bezi. A to nas dovedie k otazke ze ci by nemal takyto health endpoint nemal existovat aj u vas ;-)

A inac toto je zle, teda ak ste naozaj nechceli vracat cas spustenia aplikacie (potom zase ten javadoc je zle), skuste si to spustit 5 minut pred polnocou sa potom skusit co to urobi 5 minut po polnoci
{code}
@Service
public class BroProcessService {
    Date date = new Date(); 
     /*
      * @return	Actual date and time.
      */
    public Date getDate() {
        return date;
    }

{code}

**Comment by lisymart** [comment]
Idem na to od konca:
✓   get metoda odstranena - bola zabudnuta z predchadzajucej iteracie.
✓   Health status som kontroloval, ale pridal som kontrolu "farby", takze ak je Elastic cerveny, informuje o tom uzivatela.
✓   Logovanie s SL4J pridane, Logger odstraneny, do Elasticu ale nelogujem, pretoze to zadavatel nechcel.
X   S pouzitim ZT-exec je to horsie.Kde sa dalo, tam som ho pouzil, no nikde som nenastavil timeout, pretoze Neck sluzi na jednorazove uploadovanie suborov do Elasticu, a teda je vlakno ukoncene po nahrati dat to Elasticu. Nahravanie Gigoveho suboru moze trvat aj niekolko desiatok minut, takze seknutie vlakna by bolo na skodu. Pouzil som navod, podla ktoreho je zadany subor nahrany a proces ukonceny po dosiahnuti EOF [http://teknosrc.com/logstash-process-log-file-once-exit-stop-after-reading/](odkaz), takze k neukonceniu vlakna nedoje. Ked som sa snazil spustit ZT-exec s prikazom na nahratie suboru do Elasticu, stalo sa toto:
>  [http-bio-8080-exec-4] INFO neck.neck.LogConfig - Creating configuration file. 
>  [Thrd-1] INFO neck.neck.LogstashProcessService - /home/m/Neck/data/stored/2016-04-05-09-08-0025-conn.log/2016-04-05-09-08-0025-conn.log is being logstashed.
>  [Thrd-1] INFO neck.neck.LogstashProcessService - Error: No config files found: /home/m/Neck/03-47-0059.conf < /home/m/Neck/data/stored/2016-04-05-09-08-0025-conn.log/2016-04-05-09-08-0025-conn.log
>  Can you make sure this path is a logstash config file?
>  You may be interested in the '--configtest' flag which you can
>  use to validate logstash's configuration before you choose
to restart a running system.

Konfiguracny subor je urcite v poriadku, pretoze v extra terminali som ho pouzil a fungoval. ZT-exec jednoducho nedokaze vyhodnotit taky prikaz. Preto som tento prikaz ulozil do skriptu a vyhodnotil skript ProcessBuilderom.
(A to som skusal .command("logstash", "-f", "configFile", "<", "dataFile")
.command("logstash", "-f", "configFile < dataFile")
.command("logstash", "-f", "configFile < ", "dataFile")
.command("logstash", "-f", "configFile", "< dataFile")
ale ani jedno nefungovalo.)

Ak by ste ale boli ochotny mi poradit, ako zistim cez zt-exec, ze proces je zaseknuty a nic nerobi (tuto situaciu sice nepredpokladam), a nasledne som ho nasilu zabil, tak by som to tam rad zapracoval.

**Comment by hhulwath** [comment]
no myslim ze ste sa s tymi commandami trochu ustrelili

na toto: 
`new ProcessExecutor().command("mkdir", dirPath + "/data/pendings/" + filePath).execute();`
existuje v jave chrumkava metoda 
`Files.createDirectory(Path dir, FileAttribute<?>... attrs)  throws IOException`
nerobte cez prikaz OS nieco co viete urobit v jave
detto:
`new ProcessExecutor().directory(folder).command("rm", "-r", ".state").execute();`
sa da takto
http://www.adam-bien.com/roller/abien/entry/java_7_deleting_recursively_a ak chcete cisto cez java7
alebo ak pouzijete http://commons.apache.org/proper/commons-io/
`FileUtils.deleteDirectory(new File("directory"));`

co sa tyka tych skriptov co spustate, ja by som to riesil tak ze by som ich nevytvaral programom ale napisal nejaky shell skript (nezabidnite potom chmod na spustanie) ktory by mal na vstupe nejake vstupne parametre co tam potrebujete dostat a ten skript by bol sucastou instalacie/deploymentu a ten by som stale dookola spustal a cez ProcessBuilder by som mu fukol tie parametre a working adresar (.directory)
takze ta cesta ze ste to dali do skriptu je podla mna spravna, ale nejako by som to doupratoval, napriklad tuna: `LogstashProcessService` ale aj krizom krazom v BroProcessService  a PathsController 
Nejako by som to ucesal a vsade kde nemusite spustat externy proces to riesil volanim javou (vid hore ale aj nizsie) a cele by som to dal do jednej triedy co by obhospodorovala vsetky volania externych procesov. Potom budete to ma pokope a lahsie sa vam to doupratuje, takto je to take dost neucesane. Dobry kod vyzera pekne ;-)

a nespustajte to cez tu Future, podla mna staci nieco taketo: 
`new ProcessExecutor().command("java", "-version").timeout(60, TimeUnit.SECONDS).execute();`

no a toto tiez javista nenapise:
`ProcessExecutor().command("curl", "--silent", "http://" + EShost + "/_cluster/health")`
v springu je na to uplne chrumakva trieda
https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html
co vie rovno nacitat json (trochu googlu nezaskodi) a rovno vam tie property fukne do nejakeho POJO objektu co si pre to urobite (alebo do mapy ak napriklad potrebujete len jednu/dve hodnoty co si z tej mapy potom vytiahnete)

**Comment by hhulwath** [comment]
no a este som vobec na prvu pohlad nepochopil co robi ShowOptionsController 
takze asi to nie je uplne OK ;-) (opat dobry kod je pekny kod a tam je teda riadna motanica)
kedze to nechapem tak len nejake doporucenia

najlepsie si je posielat udaje z formulara zec nejake POJO a spring vam to z toho requestu do toho POJA fukne sam takze nemusite krvopotne parsovat request params

pre kazdu akciu (button) je najlepsie mat vlastny enpoint (urlku co handluje ten prikaz, vsetky mozu ist nasledne na rovnaky view, (kazdy subbmit buttom vlastnu form cast v html ale potom kopec hiddenov pre POJO alebo button handlovat nejaky javaskriptom co preposle submit na rozne urlky)
Ale na toto nie som odbornik

len frflrm ze kod sa mi nepaci ;-)

**Comment by lisymart** [comment]
Kde ste prisli k tomuto programu, ak mozem vediet? Prekvapuje ma, ze Vas to tak zaujima.

**Comment by hhulwath** [comment]
ste mi ho poslali

**Comment by hhulwath** [comment]
Odkaz na zdrojovy kod DP: https://github.com/lisymart/Neck
